export const URL_PATH = {
  HOME: '/home',
  MAP: '/map',
  GLOBE: '/globe',
  TIMELINE: '/timeline',
  CHARTS: '/charts',
  STYLE: '/style',
  ALPHABETICAL: '/alphabetical',
  LOCATION: '/location',
  PROGRAMMATIC: '/programmatic',
  QUIZ: '/games/quiz',
  GAMES: '/games',
  RECREATE_TIMELINE: '/games/recreate-timeline',
  GEOGUESSER: '/games/geoguesser',
  ARCHITECTURE_PUZZLE: '/games/architecture-puzzle',
  SEARCH: '/search',
  DETAIL: '/detail',
};
